#!/usr/bin/env bash
# Config server nginx for run service
echo "241" > /var/run/nginx.pid
path_src='/etc/nginx/sites-available/default'
path_dst='/etc/nginx/sites-enabled/default'
sudo rm "$path_dst"
ln -s "$path_src" "$path_dst"
