#!/usr/bin/env bash
# Config server nginx for run service
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo pkill -1 -f "/usr/sbin/nginx"
