#!/usr/bin/env bash
# check inf of holbertonschool file
filename=holbertonschool
if [ -e "$filename" ]
then
	echo "holbertonschool file exists"
	a=$(less "$filename" | wc -l)
	if ((a > 0))
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "$filename" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
